function toggleDarkMode() {
    document.body.classList.toggle('dark-mode');
    const darkModeEnabled = document.body.classList.contains('dark-mode');
    localStorage.setItem('darkMode', darkModeEnabled);
}

function applyDarkModeFromLocalStorage() {
    const darkModeEnabled = localStorage.getItem('darkMode') === 'true';
    if (darkModeEnabled) {
        document.body.classList.add('dark-mode');
    }
}

document.addEventListener('DOMContentLoaded', applyDarkModeFromLocalStorage);

if (document.body.classList.contains('anime-page')) {
    const watchedAnimeList = [
{ en: "Fairy Tail", jp: "フェアリーテイル" },
{ en: "Naruto", jp: "ナルト" },
{ en: "Naruto Shippuden", jp: "ナルト 疾風伝" },
{ en: "Boruto", jp: "BORUTO-ボルト- NARUTO NEXT GENERATIONS" },
{ en: "One Piece", jp: "ワンピース" },
{ en: "Dragon Ball", jp: "ドラゴンボール" },
{ en: "Dragon Ball Z", jp: "ドラゴンボールZ" },
{ en: "Dragon Ball GT", jp: "ドラゴンボールGT" },
{ en: "Dragon Ball Super", jp: "ドラゴンボール超" },
{ en: "Attack on Titan", jp: "進撃の巨人" },
{ en: "Tokyo Ghoul", jp: "東京喰種トーキョーグール" },
{ en: "No Game No Life", jp: "ノーゲーム・ノーライフ" },
{ en: "Parasyte the Maxim", jp: "寄生獣 セイの格率" },
{ en: "Hunter x Hunter", jp: "ハンター×ハンター" },
{ en: "Swords Art Online", jp: "ソードアート・オンライン" },
{ en: "Full Metal Alchemist Brotherhood", jp: "鋼の錬金術師 FULLMETAL ALCHEMIST" },
{ en: "One Punch Man", jp: "ワンパンマン" },
{ en: "Mirai Nikki", jp: "未来日記" },
{ en: "Shiki", jp: "屍鬼" },
{ en: "Death Parade", jp: "デス・パレード" },
{ en: "Steins Gate", jp: "シュタインズ・ゲート" },
{ en: "Another", jp: "アナザー" },
{ en: "Your Lie In April", jp: "四月は君の嘘" },
{ en: "Angel Beats", jp: "エンジェルビーツ" },
{ en: "Charlotte", jp: "シャーロット" },
{ en: "Clannad: After Story", jp: "CLANNAD ～AFTER STORY～" },
{ en: "Your name", jp: "君の名は。" },
{ en: "The Garden Of Words", jp: "言の葉の庭" },
{ en: "Corpse Party", jp: "コープスパーティー" },
{ en: "One Week Friends", jp: "一週間フレンズ" },
{ en: "Himouto! Umaru-chan", jp: "干物妹!うまるちゃん" },
{ en: "Assassination Classroom", jp: "暗殺教室" },
{ en: "WataMote", jp: "私がモテないのはどう考えてもお前らが悪い!" },
{ en: "Oreimo", jp: "俺の妹がこんなに可愛いわけがない" },
{ en: "Magi", jp: "マギ" },
{ en: "Food Wars!", jp: "食戟のソーマ" },
{ en: "Nisekoi", jp: "ニセコイ" },
{ en: "Noragami", jp: "ノラガミ" },
{ en: "Golden Time", jp: "ゴールデンタイム" },
{ en: "Place to Place", jp: "あっちこっち" },
{ en: "Beyond the Boundary", jp: "境界の彼方" },
{ en: "Prison School", jp: "監獄学園" },
{ en: "Blue Spring Ride", jp: "アオハライド" },
{ en: "Death Note", jp: "デスノート" },
{ en: "A Channel", jp: "Aチャンネル" },
{ en: "New Game!", jp: "NEW GAME!" },
{ en: "Classroom of the Elite", jp: "ようこそ実力至上主義の教室へ" },
{ en: "Yuru Yuri", jp: "ゆるゆり" },
{ en: "Anne Happy", jp: "あんハピ♪" },
{ en: "Amagami SS", jp: "アマガミSS" },
{ en: "Hotarubi no mori e", jp: "蛍火の杜へ" },
{ en: "Senyuu", jp: "戦勇。" },
{ en: "Deadman Wonderland", jp: "デッドマン・ワンダーランド" },
{ en: "Devil is a part-timer", jp: "はたらく魔王さま!" },
{ en: "K: Return of Kings", jp: "K RETURN OF KINGS" },
{ en: "Tanaka-kun wa Itsumo Kedaruge", jp: "田中くんはいつもけだるげ" },
{ en: "Higurashi Series", jp: "ひぐらしのなく頃に" },
{ en: "Tokyo Magnitude 8.0", jp: "東京マグニチュード8.0" },
{ en: "Glasslip", jp: "グラスリップ" },
{ en: "Haikyuu!!", jp: "ハイキュー!!" },
{ en: "Toradora", jp: "とらドラ!" },
{ en: "Erased", jp: "僕だけがいない街" },
{ en: "Chuunibyou Demo Koi Ga Shitai! Ren", jp: "中二病でも恋がしたい!戀" },
{ en: "Danganronpa", jp: "ダンガンロンパ" },
{ en: "K-On", jp: "けいおん!" },
{ en: "Miss Kobayashi's Dragon Maid", jp: "小林さんちのメイドラゴン" },
{ en: "Re:Zero", jp: "Re:ゼロから始める異世界生活" },
{ en: "Bungo Stray Dogs", jp: "文豪ストレイドッグス" },
{ en: "Hanasuka Iroha", jp: "花咲くいろは" },
{ en: "Plastic Memories", jp: "プラスティック・メモリーズ" },
{ en: "Kinmoza", jp: "きんいろモザイク" },
{ en: "BTOOOM", jp: "ブトゥーム" },
{ en: "Divine Gate", jp: "ディバインゲート" },
{ en: "Wagnaria", jp: "ワーキング!!" },
{ en: "Guilty Crown", jp: "ギルティクラウン" },
{ en: "Anohana", jp: "あの日見た花の名前を僕達はまだ知らない。" },
{ en: "Beelzebub", jp: "べるぜバブ" },
{ en: "Terror in Resonance", jp: "残響のテロル" },
{ en: "Kimi no Todoke", jp: "君に届け" },
{ en: "Hell Girl", jp: "地獄少女" },
{ en: "Konosuba", jp: "この素晴らしい世界に祝福を!" },
{ en: "School Days", jp: "スクールデイズ" },
{ en: "King's Game", jp: "王様ゲーム" },
{ en: "Jormungand", jp: "ヨルムンガンド" },
{ en: "ReLife", jp: "リライフ" },
{ en: "Psycho Pass", jp: "サイコパス" },
{ en: "Trinity Seven", jp: "トリニティセブン" },
{ en: "Non Non Biyori", jp: "のんのんびより" },
{ en: "Tsuredure Children", jp: "徒然チルドレン" },
{ en: "Fastest Finger First", jp: "ナナマル サンバツ" },
{ en: "Love is Like a Cocktail", jp: "お酒は夫婦になってから" },
{ en: "Mushishi", jp: "蟲師" },
{ en: "91 Days", jp: "91デイズ" },
{ en: "Gamers ", jp: "ゲーマーズ!" },
{ en: "Hamatora", jp: "ハマトラ" },
{ en: "Jokers Game", jp: "ジョーカー・ゲーム" },
{ en: "Baka & Test", jp: "バカとテストと召喚獣" },
{ en: "Gunslinger Girl", jp: "ガンスリンガー・ガール" },
{ en: "Elfen Lied", jp: "エルフェンリート" },
{ en: "5 Centimeters per Second", jp: "秒速5センチメートル" },
{ en: "D-Frag", jp: "ディーふらぐ！" },
{ en: "The Melancholy of Haruhi Suzumiya", jp: "涼宮ハルヒの憂鬱" },
{ en: "Recovery of an MMO Junkie", jp: "ネト充のススメ" },
{ en: "Anti-Magic Academy", jp: "対魔導学園35試験小隊" },
{ en: "Blend-S", jp: "ブレンド・S" },
{ en: "Pandora Hearts", jp: "パンドラハーツ" },
{ en: "School-Live", jp: "がっこうぐらし！" },
{ en: "Hand-Shakers", jp: "ハンドシェイカー" },
{ en: "Kill la Kill", jp: "キルラキル" },
{ en: "Kokoro Connect", jp: "ココロコネクト" },
{ en: "Anime-Gataris", jp: "アニメガタリズ" },
{ en: "Juuni Taisen", jp: "十二大戦" },
{ en: "Imouto sae Ireba Ii", jp: "妹さえいればいい。" },
{ en: "Black Clover", jp: "ブラッククローバー" },
{ en: "Little Busters!", jp: "リトルバスターズ！" },
{ en: "Bloodivores", jp: "ブラッディヴォーレス" },
{ en: "Cheating Craft ", jp: "チーティングクラフト" },
{ en: "Sakura Quest", jp: "サクラクエスト" },
{ en: "DanMachi", jp: "ダンまち" },
{ en: "Yuru Camp", jp: "ゆるキャン△" },
{ en: "Ramen Daisuki Koizumi-San ", jp: "ラーメン大好き小泉さん" },
{ en: "Log Horizon", jp: "ログ・ホライズン" },
{ en: "Gabriel DropOut", jp: "ガヴリールドロップアウト" },
{ en: "A Centaur's Life ", jp: "セントールの悩み" },
{ en: "Sabagebu", jp: "さばげぶっ！" },
{ en: "Slow Start", jp: "スロウスタート" },
{ en: "Scorching Ping Pong Girls", jp: "灼熱の卓球娘" },
{ en: "Hal", jp: "ハル" },
{ en: "Tsukigakerei", jp: "月がきれい" },
{ en: "Ef", jp: "エフ" },
{ en: "Aho-Girl", jp: "アホガール" },
{ en: "Alice & Zoroku", jp: "アリスと蔵六" },
{ en: "Karakai Jozu No Takagi-San", jp: "からかい上手の高木さん" },
{ en: "Chronicles of the Going Home Club", jp: "帰宅部活動記録" },
{ en: "A Place Further Than The Universe", jp: "宇宙よりも遠い場所" },
{ en: "Interviews with Monster Girls", jp: "亜人ちゃんは語りたい" },
{ en: "Night Raid 1931", jp: "夜ノヤッターマン" },
{ en: "Denki-Gai", jp: "デンキ街の本屋さん" },
{ en: "Restaurant to Another World", jp: "異世界食堂" },
{ en: "My Teen Romantic Comedy SNAFU", jp: "やはり俺の青春ラブコメはまちがっている。" },
{ en: "Shelter", jp: "シェルター" },
{ en: "Gate", jp: "ゲート 自衛隊 彼の地にて、斯く戦えり" },
{ en: "Eromanga Sensei", jp: "エロマンガ先生" },
{ en: "The World God Only Knows", jp: "神のみぞ知るセカイ" },
{ en: "Boku no Hero Academia", jp: "僕のヒーローアカデミア" },
{ en: "The Ryuo's Work is Never Done", jp: "りゅうおうのおしごと！" },
{ en: "Berserk ", jp: "ベルセルク" },
{ en: "Citrus", jp: "シトラス" },
{ en: "Masamune-kun's Revenge", jp: "政宗くんのリベンジ" },
{ en: "Servant x Service", jp: "サーバント×サービス" },
{ en: "My First Girlfriend is a Gal", jp: "はじめてのギャル" },
{ en: "Gekkan Shoujo Nozaki-kun", jp: "月刊少女野崎くん" },
{ en: "My Little Monster", jp: "となりの怪物くん" },
{ en: "Love Tyrant", jp: "恋愛暴君" },
{ en: "3-gatsu no Lion", jp: "3月のライオン" },
{ en: "Orange", jp: "オレンジ" },
{ en: "ReWrite", jp: "Rewrite" },
{ en: "ALDNOAH.ZERO", jp: "アルドノア・ゼロ" },
{ en: "Seraph of the End", jp: "終わりのセラフ" },
{ en: "White Album", jp: "ホワイトアルバム" },
{ en: "White Album 2", jp: "ホワイトアルバム2" },
{ en: "The Ancient Magus' Bride", jp: "魔法使いの嫁" },
{ en: "Comic Girls", jp: "こみっくがーるず" },
{ en: "My Sweet Tyrant", jp: "あっくんとカノジョ" },
{ en: "Overlord", jp: "オーバーロード" },
{ en: "DARLING in the FRANXX", jp: "ダーリン・イン・ザ・フランキス" },
{ en: "Crossing Time", jp: "踏切時間" },
{ en: "Snow White with the Red Hair", jp: "赤髪の白雪姫" },
{ en: "Hinamatsuri", jp: "ヒナまつり" },
{ en: "Locodol", jp: "普通の女子校生が【ろこどる】やってみた。" },
{ en: "Amanchu!", jp: "あまんちゅ！" },
{ en: "Welcome to the N-H-K", jp: "NHKにようこそ！" },
{ en: "Mob Psycho 100", jp: "モブサイコ100" },
{ en: "Love Lab", jp: "ラブライブ！" },
{ en: "Yotsuiro Biyori", jp: "四月は君の嘘" },
{ en: "The Idol Master", jp: "アイドルマスター" },
{ en: "THE IDOLM@STER CINDERELLA GIRLS", jp: "アイドルマスター シンデレラガールズ" },
{ en: "You Don't Know Gunma Yet", jp: "お前はまだグンマを知らない" },
{ en: "PERSONA5", jp: "ペルソナ5" },
{ en: "Love Live! School Idol Project", jp: "ラブライブ！スクールアイドルプロジェクト" },
{ en: "Love Live! Sunshine!!", jp: "ラブライブ！サンシャイン!!" },
{ en: "Hakata Tonkotsu Ramens", jp: "博多豚骨ラーメンズ" },
{ en: "No.6", jp: "ナンバー・シックス" },
{ en: "Grimgar of Fantasy and Ash", jp: "灰と幻想のグリムガル" },
{ en: "Kakegurui", jp: "賭ケグルイ" },
{ en: "The Disastrous Life of Saiki K.", jp: "斉木楠雄のΨ難" },
{ en: "The Seven Deadly Sins", jp: "七つの大罪" },
{ en: "Hyouka", jp: "氷菓" },
{ en: "Violet Evergarden ", jp: "ヴァイオレット・エヴァーガーデン" },
{ en: "Durarara", jp: "デュラララ!!" },
{ en: "Dagashi Kashi", jp: "だがしかし" },
{ en: "Gakuen Babysitters", jp: "学園ベビーシッターズ" },
{ en: "HENNEKO", jp: "変態王子と笑わない猫。" },
{ en: "Black Butler", jp: "黒執事" },
{ en: "The Pet Girl of Sakurasou", jp: "さくら荘のペットな彼女" },
{ en: "Gintama ", jp: "銀魂" },
{ en: "My Love Story!!", jp: "俺物語!!" },
{ en: "Record of Grancrest War", jp: "グランクレスト戦記" },
{ en: "Island", jp: "アイランド" },
{ en: "Angels of Death", jp: "殺戮の天使" },
{ en: "Chio's School Road", jp: "ちおちゃんの通学路" },
{ en: "Cells at Work", jp: "はたらく細胞" },
{ en: "Asobi Asobase", jp: "あそびあそばせ" },
{ en: "Saga of Tanya the Evil", jp: "幼女戦記" },
{ en: "Barakamon", jp: "ばらかもん" },
{ en: "Dantalian no Shoka", jp: "ダンタリアンの書架" },
{ en: "Nichijou", jp: "日常" },
{ en: "Gosick", jp: "ゴシック" },
{ en: "Komori-san Can't Decline!", jp: "こもりさんは断れない!" },
{ en: "Ano Natsu de Matteru", jp: "あの夏で待ってる" },
{ en: "Blue Exorcist ", jp: "青の祓魔師" },
{ en: "Myself; Yourself ", jp: "マイセルフ；ユアセルフ" },
{ en: "Soul Eater", jp: "ソウルイーター" },
{ en: "Soul Eater Not!", jp: "ソウルイーターノット!" },
{ en: "Akame ga Kill", jp: "アカメが斬る!" },
{ en: "Yukushiki", jp: "ゆゆ式" },
{ en: "Shin Sekai Yori", jp: "新世界より" },
{ en: "Upotte!!", jp: "うぽって!!" },
{ en: "Eden of the East", jp: "東のエデン" },
{ en: "Serial Experiment Lain", jp: "シリアルエクスペリメンツ・レイン" },
{ en: "Riddle Story of Devil", jp: "悪魔のリドル" },
{ en: "In Search of the Lost Future", jp: "失われた未来を求めて" },
{ en: "Inu X Boku", jp: "妖狐×僕SS" },
{ en: "Mysterious Girlfriend X", jp: "謎の彼女X" },
{ en: "sweetness & lightning", jp: "甘々と稲妻" },
{ en: "Yamishibai: Japanese Ghost Stories", jp: "闇芝居" },
{ en: "Junji Ito Collection", jp: "伊藤潤二コレクション" },
{ en: "RErideD - Derrida, who leaps though time", jp: "RErideD-刻越えのデリダ" },
{ en: "Frankenstein Family", jp: "怪物事変" },
{ en: "My Wife is the Student Council President ", jp: "おくさまが生徒会長!" },
{ en: "Dusk Maiden of Amnesia", jp: "黄昏乙女×アムネジア" },
{ en: "Time of Eve", jp: "イヴの時間" },
{ en: "Mizu no Kotoba", jp: "水のコトバ" },
{ en: "Shimoneta", jp: "下ネタという概念が存在しない退屈な世界" },
{ en: "The Time I Got Reincarnated as a Slime", jp: "転生したらスライムだった件" },
{ en: "Rascal Does Not Dream of Bunny Girl Senpai", jp: "青春ブタ野郎はバニーガール先輩の夢を見ない" },
{ en: "Zombie Land Saga", jp: "ゾンビランドサガ" },
{ en: "Code Geass", jp: "コードギアス" },
{ en: "Goblin Slayer", jp: "ゴブリンスレイヤー" },
{ en: "Danshi Koukousei no Nichijou", jp: "男子高校生の日常" },
{ en: "Dog & Scissors ", jp: "犬とハサミは使いよう" },
{ en: "A Certain Magical Index", jp: "とある魔術の禁書目録" },
{ en: "Patema Inverted", jp: "サカサマのパテマ" },
{ en: "A Lull in the Sea", jp: "凪のあすから" },
{ en: "Punch Line", jp: "パンチライン" },
{ en: "Hyakko", jp: "ひゃっこ" },
{ en: "Hinomaru Sumo", jp: "火ノ丸相撲" },
{ en: "Fate/Stay Night", jp: "Fate/stay night" },
{ en: "Fate/Zero", jp: "Fate/Zero" },
{ en: "Toriko", jp: "トリコ" },
{ en: "Squid Girl", jp: "侵略！イカ娘" },
{ en: "Yamada-kun and the Seven Witches", jp: "山田くんと7人の魔女" },
{ en: "Kiznaiver", jp: "キズナイーバー" },
{ en: "Monster Musume", jp: "モンスター娘のいる日常" },
{ en: "Occult;Nine", jp: "オカルティック・ナイン" },
{ en: "Golden Kamuy", jp: "ゴールデンカムイ" },
{ en: "Bakuon!!", jp: "ばくおん!!" },
{ en: "Koe no Katachi", jp: "聲の形" },
{ en: "Ookami Kodomo no Ame Yuki ", jp: "おおかみこどもの雨と雪" },
{ en: "Magical Girl Raising Project", jp: "魔法少女育成計画" },
{ en: "Evangelion", jp: "新世紀エヴァンゲリオン" },
{ en: "Grand Blue", jp: "ぐらんぶる" },
{ en: "Bloom Into You", jp: "やがて君になる" },
{ en: "Happy Sugar Life", jp: "ハッピーシュガーライフ" },
{ en: "Wotaku ni Koi wa Muzukashii", jp: "ヲタクに恋は難しい" },
{ en: "Mahou Shoujo Site", jp: "魔法少女サイト" },
{ en: "Boogiepop and Others", jp: "ブギーポップは笑わない" },
{ en: "The Rising of the Shield Hero", jp: "盾の勇者の成り上がり" },
{ en: "The Promised Neverland", jp: "約束のネバーランド" },
{ en: "Hi Score Girl", jp: "ハイスコアガール" },
{ en: "Back Street Girls: Gokudols", jp: "Back Street Girls -ゴクドルズ-" },
{ en: "Mitsuboshi Colors", jp: "三ツ星カラーズ" },
{ en: "My Roommate is a Cat", jp: "同居人はひざ、時々、頭のうえ。" },
{ en: "WATATEN! An Angel Flew Down to Me", jp: "私に天使が舞い降りた!" },
{ en: "3D Kanojo: Real Girl", jp: "3D彼女 リアルガール" },
{ en: "Flying Witch", jp: "ふらいんぐうぃっち" },
{ en: "Kaguya-Sama: Love Is War", jp: "かぐや様は告らせたい～天才たちの恋愛頭脳戦～" },
{ en: "The Quintessential Quintuplets", jp: "五等分の花嫁" },
{ en: "I Want To Eat Your Pancreas", jp: "君の膵臓をたべたい" },
{ en: "SSSS.GRIDMAN", jp: "SSSS.GRIDMAN" },
{ en: "Perfect Blue", jp: "パーフェクトブルー" },
{ en: "Omoide No Marnie", jp: "思い出のマーニー" },
{ en: "Maquia: When The Promised Flower Blooms", jp: "さよならの朝に約束の花をかざろう" },
{ en: "How Not To Summon A Demon Lord", jp: "異世界魔王と召喚少女の奴隷魔術" },
{ en: "The Price of Smiles", jp: "エガオノダイカ" },
{ en: "Lucky Star", jp: "らき☆すた" },
{ en: "Bleach", jp: "ブリーチ" },
{ en: "Domestic Girlfriend", jp: "ドメスティックな彼女" },
{ en: "The Royal Tutor", jp: "王室教師ハイネ" },
{ en: "Aoharu x Machinegun", jp: "青春×機関銃" },
{ en: "Flip Flappers", jp: "フリップフラッパーズ" },
{ en: "Run with the Wind", jp: "風が強く吹いている" },
{ en: "How clumsy you are, Miss Ueno.", jp: "上野さんは不器用" },
{ en: "Fruits Basket", jp: "フルーツバスケット" },
{ en: "Hitoribocchi no Marumaruseikatsu", jp: "ひとりぼっちの○○生活" },
{ en: "Joshi Kausei", jp: "女子かう生" },
{ en: "Nobunaga teacher's young bride", jp: "ノブナガ先生の幼な妻" },
{ en: "Demon Slayer: Kimetsu no Yaiba", jp: "鬼滅の刃" },
{ en: "We Never Learn: BOKUBEN", jp: "ぼくたちは勉強ができない" },
{ en: "Black Bullet", jp: "ブラック・ブレット" },
{ en: "GJ Club", jp: "GJ部" },
{ en: "Senryu Girl", jp: "川柳少女" },
{ en: "Ao-chan Can't Study!", jp: "淫らな青ちゃんは勉強ができない" },
{ en: "Usagi Drop", jp: "うさぎドロップ" },
{ en: "The Morose Mononokean", jp: "不機嫌なモノノケ庵" },
{ en: "Chihayafuru", jp: "ちはやふる" },
{ en: "GTO", jp: "GTO" },
{ en: "Silver Spoon", jp: "銀の匙" },
{ en: "Wise Man's Grandchild", jp: "賢者の孫" },
{ en: "Honey and Clover", jp: "ハチミツとクローバー" },
{ en: "Liz to Aoi Tori", jp: "リズと青い鳥" },
{ en: "Kimi no Koe wo Todoketai", jp: "君の声を届けたい" },
{ en: "Summer Wars", jp: "サマーウォーズ" },
{ en: "Flavors of Youth", jp: "詩季織々" },
{ en: "Alderamin on the Sky", jp: "ねじ巻き精霊戦記 天鏡のアルデラミン" },
{ en: "Banana Fish", jp: "BANANA FISH" },
{ en: "Made in Abyss", jp: "メイドインアビス" },
{ en: "Monster", jp: "MONSTER" },
{ en: "Handa-kun", jp: "はんだくん" },
{ en: "Magical Sempai", jp: "手品先輩" },
{ en: "Are You Lost?", jp: "ソウナンですか？" },
{ en: "Fire Force", jp: "炎炎ノ消防隊" },
{ en: "Dr. Stone", jp: "ドクターストーン" },
{ en: "If It’s For My Daughter, I’d Even Defeat a Demon Lord", jp: "娘のためならば、俺はもしかしたら魔王も倒せるかもしれない。" },
{ en: "Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?", jp: "通常攻撃が全体攻撃で二回攻撃のお母さんは好きですか？" },
{ en: "The Anthem of the Heart", jp: "心が叫びたがってるんだ。" },
{ en: "The Girl Who Leapt Through Time", jp: "時をかける少女" },
{ en: "Rainbow: Nisha Rokubou no Shichinin", jp: "虹色デイズ" },
{ en: "Koi to Uso", jp: "恋と嘘" },
{ en: "JoJo", jp: "ジョジョ" },
{ en: "Araburu Kisetsu no Otome-domo yo", jp: "荒ぶる季節の乙女どもよ。" },
{ en: "Cop Craft", jp: "コップクラフト" },
{ en: "Natsume Yuujin-Chou", jp: "夏目友人帳" },
{ en: "Gurren Lagann", jp: "天元突破グレンラガン" },
{ en: "SKET Dance", jp: "スケットダンス" },
{ en: "BlackFox", jp: "ブラックフォックス" },
{ en: "Showa Genroku Rakugo Shinju", jp: "昭和元禄落語心中" },
{ en: "ORESUKI", jp: "俺好き" },
{ en: "Welcome to Demon School! Iruma-kun", jp: "魔入りました！入間くん" },
{ en: "Assassins Pride", jp: "アサシンズプライド" },
{ en: "Joshikousei no Mudazukai", jp: "女子高生の無駄づかい" },
{ en: "Binbougami Ga!", jp: "貧乏神が!" },
{ en: "Nana", jp: "NANA" },
{ en: "Skip Beat!", jp: "スキップ・ビート!" },
{ en: "Engaged to the Unidentified", jp: "未確認で進行形" },
{ en: "Blast of Tempest", jp: "絶園のテンペスト" },
{ en: "Tada-kun wa koi wo shinai", jp: "多田くんは恋をしない" },
{ en: "Tamako Market", jp: "たまこマーケット" },
{ en: "Strawberry Marshmallow", jp: "苺ましまろ" },
{ en: "Maid-Sama!", jp: "会長はメイド様!" },
{ en: "Fate/Grand Order: Babylonia", jp: "Fate/Grand Order -絶対魔獣戦線バビロニア-" },
{ en: "Fate/Stay Night Movie: Heaven’s Feel", jp: "劇場版 Fate/stay night [Heaven's Feel]" },
{ en: "Kabaneri of the Iron Fortress", jp: "甲鉄城のカバネリ" },
{ en: "Kids on the Slope", jp: "坂道のアポロン" },
{ en: "Inuyasha", jp: "犬夜叉" },
{ en: "Arakawa Under the Bridge", jp: "荒川アンダー ザ ブリッジ" },
{ en: "Girls’ Last Tour", jp: "少女終末旅行" },
{ en: "ShiroBako", jp: "SHIROBAKO" },
{ en: "Tonari no Seki-kun", jp: "となりの関くん" },
{ en: "Oreshura", jp: "俺の彼女と幼なじみが修羅場すぎる" },
{ en: "Vinland Saga", jp: "ヴィンランド・サガ" },
{ en: "Kotoura-San", jp: "琴浦さん" },
{ en: "Keep Your Hands Off Eizouken!", jp: "映像研には手を出すな!" },
{ en: "A Destructive God Sits Next To Me", jp: "ぼくのとなりに暗黒破壊神がいます。" },
{ en: "Houseki no Kuni", jp: "宝石の国" },
{ en: "The Demon Girl Next Door", jp: "まちカドまぞく" },
{ en: "Ishuzoku Reviewers", jp: "異種族レビュアーズ" },
{ en: "Lovely Complex", jp: "ラブ★コン" },
{ en: "Ms.Vampire who lives in my neighborhood", jp: "となりの吸血鬼さん" },
{ en: "The Irregular at Magic High School", jp: "魔法科高校の劣等生" },
{ en: "FLCL", jp: "フリクリ" },
{ en: "Carole and Tuesday", jp: "キャロル&チューズデイ" },
{ en: "Seton Academy", jp: "群れなせ！シートン学園" },
{ en: "Darwin’s Game", jp: "ダーウィンズゲーム" },
{ en: "In/Spectre", jp: "虚構推理" },
{ en: "Colorful", jp: "カラフル" },
{ en: "Promare", jp: "プロメア" },
{ en: "Grave of the Fireflies", jp: "火垂るの墓" },
{ en: "Spirited Away", jp: "千と千尋の神隠し" },
{ en: "Howls Moving Castle", jp: "ハウルの動く城" },
{ en: "Jibaku Shounen Hanako-kun", jp: "地縛少年花子くん" },
{ en: "Hana Yori Dango", jp: "花より男子" },
{ en: "Dororo", jp: "どろろ" },
{ en: "Id:Invaded", jp: "ID:INVADED" },
{ en: "Izetta: The Last Witch", jp: "終末のイゼッタ" },
{ en: "Samurai Champloo", jp: "サムライチャンプルー" },
{ en: "Bakuman", jp: "バクマン。" },
{ en: "Tower of God", jp: "神之塔" },
{ en: "Sing “Yesterday” For Me", jp: "イエスタデイをうたって" },
{ en: "My Next Life as a Villainess", jp: "乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった…" },
{ en: "Hanamaru Kindergarten", jp: "はなまる幼稚園" },
{ en: "Is the Order a Rabbit?", jp: "ご注文はうさぎですか？" },
{ en: "Princess Connect! Re: Dive", jp: "プリンセスコネクト！Re:Dive" },
{ en: "Baccano!", jp: "バッカーノ!" },
{ en: "Tenki no ko", jp: "天気の子" },
{ en: "Kingdom", jp: "キングダム" },
{ en: "Megalobox", jp: "メガロボクス" },
{ en: "This Art Club Has a Problem!", jp: "この美術部には問題がある！" },
{ en: "Kakushigoto", jp: "かくしごと" },
{ en: "Whisper of the Heart", jp: "耳をすませば" },
{ en: "Hayate the Combat Butler!", jp: "ハヤテのごとく！" },
{ en: "DECA-DENCE", jp: "デカダンス" },
{ en: "Diary of our days at the breakwater", jp: "放課後ていぼう日誌" },
{ en: "Uzaki-chan Wants To Hang Out!", jp: "宇崎ちゃんは遊びたい！" },
{ en: "Rent-a-Girlfriend", jp: "彼女、お借りします" },
{ en: "Astra Lost In Space", jp: "彼方のアストラ" },
{ en: "Great Pretender", jp: "グレートプリテンダー" },
{ en: "Nihon Chinbotsu 2020", jp: "日本沈没2020" },
{ en: "Kono Oto Tomare!", jp: "この音とまれ！" },
{ en: "Ani ni Tsukeru Kusuri wa Nai!", jp: "兄に付ける薬はない！" },
{ en: "Mahou Shoujo Madoka Magica", jp: "魔法少女まどか☆マギカ" },
{ en: "Fugou Keiji: Balanced:Unlimited", jp: "富豪刑事 Balance:UNLIMITED" },
{ en: "Spice and Wolf", jp: "狼と香辛料" },
{ en: "Dropkick on my Devil!", jp: "邪神ちゃんドロップキック" },
{ en: "The Misfit of Demon King Academy", jp: "魔王学院の不適合者" },
{ en: "Bakemono no Ko", jp: "バケモノの子" },
{ en: "Bakemonogatari", jp: "化物語" },
{ en: "Katanagatari", jp: "刀語" },
{ en: "Kizumonogatari", jp: "傷物語" },
{ en: "Nisemonogatari", jp: "偽物語" },
{ en: "Nekomonogatari", jp: "猫物語" },
{ en: "Ginga Eiyuu Densetsu", jp: "銀河英雄伝説" },
{ en: "I can’t understand what my husband is saying", jp: "旦那が何を言っているかわからない件" },
{ en: "Kannagi", jp: "かんなぎ" },
{ en: "Burn the Witch", jp: "BURN THE WITCH" },
{ en: "I'm Standing on a Million Lives", jp: "100万の命の上に俺は立っている" },
{ en: "Jujutsu Kaisen", jp: "呪術廻戦" },
{ en: "Tonikaku Kawaii", jp: "トニカクカワイイ" },
{ en: "Hanyou no Yashahime", jp: "半妖の夜叉姫" },
{ en: "Adachi to Shimamura", jp: "安達としまむら" },
{ en: "Taisou Zamurai", jp: "体操ザムライ" },
{ en: "Majo no Tabitabi", jp: "魔女の旅々" },
{ en: "Azumanga Daioh", jp: "あずまんが大王" },
{ en: "Osomatsu-san", jp: "おそ松さん" },
{ en: "Konohana Kitan", jp: "此花亭奇譚" },
{ en: "Kara no Kyoukai", jp: "空の境界" },
{ en: "Kino no Tabi", jp: "キノの旅" },
{ en: "Akudama Drive", jp: "アクダマドライブ" },
{ en: "Genshiken", jp: "げんしけん" },
{ en: "Mitsudomoe", jp: "みつどもえ" },
{ en: "Minami-ke", jp: "みなみけ" },
{ en: "Phantom", jp: "ファントム" },
{ en: "Mawaru Penguindrum", jp: "輪るピングドラム" },
{ en: "Tenchi Souzou Design-bu", jp: "天地創造デザイン部" },
{ en: "Jaku-Chara Tomozaki-kun", jp: "弱キャラ友崎くん" },
{ en: "Horimiya", jp: "ホリミヤ" },
{ en: "Mushoku Tensei: Jobless Reincarnation", jp: "無職転生 ～異世界行ったら本気だす～" },
{ en: "Kemono Jihen", jp: "怪物事変" },
{ en: "Wonder Egg Priority", jp: "ワンダーエッグ・プライオリティ" },
{ en: "Yuukoku no Moriarty", jp: "憂国のモリアーティ" },
{ en: "Ben-To", jp: "ベン・トー" },
{ en: "Air TV", jp: "AIR" },
{ en: "Munou no Nana", jp: "無能なナナ" },
{ en: "Pui Pui Molcar", jp: "PUI PUI モルカー" },
{ en: "Kumo Desu ga, Nani ka?", jp: "蜘蛛ですが、なにか？" },
{ en: "Yowamushi Pedal", jp: "弱虫ペダル" },
{ en: "Hinako Note", jp: "ひなこのーと" },
{ en: "Sewayaki Kitsune no Senko-san", jp: "世話やきキツネの仙狐さん" },
{ en: "Urara Meirochou", jp: "うらら迷路帖" },
{ en: "Amagami Brilliant Park", jp: "甘城ブリリアントパーク" },
{ en: "Ookami-San and Her Seven Companions", jp: "オオカミさんと七人の仲間たち" },
{ en: "Ghost Hound", jp: "神霊狩" },
{ en: "Seitokai Yakuindomo", jp: "生徒会役員共" },
{ en: "Hourou Musuko", jp: "放浪息子" },
{ en: "Joshiraku", jp: "じょしらく" },
{ en: "Edens Zero", jp: "EDENS ZERO" },
{ en: "Tokyo Revengers", jp: "東京リベンジャーズ" },
{ en: "SSSS.Dynazenon", jp: "SSSS.DYNAZENON" },
{ en: "Shaman King", jp: "シャーマンキング" },
{ en: "Vivy Fluorite Eyes Song", jp: "Vivy -Fluorite Eye’s Song-" },
{ en: "Sentouin, Hakenshimasu", jp: "戦闘員、派遣します！" },
{ en: "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway", jp: "ひげを剃る。そして女子高生を拾う。" },
{ en: "Yakunara Mug Cup Mo", jp: "やくならマグカップも" },
{ en: "Super Cub", jp: "スーパーカブ" },
{ en: "Gokushufudou", jp: "極主夫道" },
{ en: "Ijiranaide, Nagatora-san", jp: "イジらないで、長瀞さん" },
{ en: "86", jp: "86-エイティシックス-" },
{ en: "Shadows House", jp: "シャドーハウス" },
{ en: "Fumetsu no Anata e", jp: "不滅のあなたへ" },
{ en: "Black Lagoon", jp: "ブラック・ラグーン" },
{ en: "Oruchuban Ebichu", jp: "おるちゅばんエビちゅ" },
{ en: "Hellsing", jp: "ヘルシング" },
{ en: "Romeo x Juliet", jp: "ロミオ×ジュリエット" },
{ en: "Kanon", jp: "Kanon" },
{ en: "Kill me baby", jp: "キルミーベイベー" },
{ en: "Aria", jp: "ARIA" },
{ en: "High school of the dead", jp: "学園黙示録 HIGHSCHOOL OF THE DEAD" },
{ en: "Totsukuni no Shoujo", jp: "とつくにの少女" },
{ en: "Sansha Sanyou", jp: "三者三葉" },
{ en: "Date a Live", jp: "デート・ア・ライブ" },
{ en: "Paradise Kiss", jp: "パラダイス・キス" },
{ en: "Ballroom e Youkoso", jp: "ボールルームへようこそ" },
{ en: "Haiyoru! Nyaruko-san", jp: "這いよれ！ニャル子さん" },
{ en: "Kuzu no Honkai", jp: "クズの本懐" },
{ en: "Haibane Renmei", jp: "灰羽連盟" },
{ en: "D.Gray Man", jp: "D.Gray-man" },
{ en: "Cross Game", jp: "クロスゲーム" },
{ en: "Odd Taxi", jp: "オッドタクシー" },
{ en: "Slime Taoshite 300-nen, Shiranai Uchi ni Level Max ni Nattemashita", jp: "スライム倒して300年、知らないうちにレベルMAXになってました" },
{ en: "Nodame Cantabile", jp: "のだめカンタービレ" },
{ en: "Full Metal Panic", jp: "フルメタル・パニック！" },
{ en: "Kaiji", jp: "カイジ" },
{ en: "Chuukan Kanriroku Tonegawa", jp: "中間管理録トネガワ" },
{ en: "Hibike! Euphorium", jp: "響け！ユーフォニアム" },
{ en: "Uma Musume", jp: "ウマ娘 プリティーダービー" },
{ en: "Saki", jp: "咲-Saki-" },
{ en: "Tamayura", jp: "たまゆら" },
{ en: "Hajime no Ippo", jp: "はじめの一歩" },
{ en: "Vanitas No Carte", jp: "ヴァニタスの手記" },
{ en: "The Detective Is Already Dead", jp: "探偵はもう、死んでいる。" },
{ en: "Shiroi Suna no Aquatope", jp: "白い砂のアクアトープ" },
{ en: "The Duke of Death and his Maid", jp: "死神坊ちゃんと黒メイド" },
{ en: "Jahy Sama Wa Kujikenai", jp: "ジャヒー様はくじけない！" },
{ en: "Sonny Boy", jp: "ソニーボーイ" },
{ en: "Bokutachi no Remake", jp: "ぼくたちのリメイク" },
{ en: "Maria Holic", jp: "まりあ†ほりっく" },
{ en: "Battle Game in 5 Seconds", jp: "出会って5秒でバトル" },
{ en: "Uramichi Oniisan", jp: "うらみちお兄さん" },
{ en: "Special A", jp: "S・A〜スペシャル・エー〜" },
{ en: "Rokka no Yuusha", jp: "六花の勇者" },
{ en: "Josee to Tora to Sakana-tachi", jp: "ジョゼと虎と魚たち" },
{ en: "Hanamonogatari", jp: "花物語" },
{ en: "Tsukimonogatari", jp: "憑物語" },
{ en: "Koyomimonogatari", jp: "暦物語" },
{ en: "Owarimonogatari", jp: "終物語" },
{ en: "Beck", jp: "BECK" },
{ en: "Trigun", jp: "トライガン" },
{ en: "Cromartie High School", jp: "魁!!クロマティ高校" },
{ en: "Tawawa on Monday", jp: "月曜日のたわわ" },
{ en: "Ganbare Douki Chan", jp: "がんばれ同期ちゃん" },
{ en: "Komi San Wa Comyushou Desu", jp: "古見さんは、コミュ症です。" },
{ en: "Blue Period", jp: "ブルーピリオド" },
{ en: "Our Love Has Always Been 10 Cent. Apart", jp: "ずっと前から好きでした。～告白実行委員会～" },
{ en: "I’ve always liked you", jp: "好きになるその瞬間を。〜告白実行委員会〜" },
{ en: "The moment you fall in love", jp: "ずっと前から好きでした。～告白実行委員会～" },
{ en: "Prince of Tennis", jp: "テニスの王子様" },
{ en: "Mieruko Chan", jp: "見える子ちゃん" },
{ en: "takt op destiny", jp: "takt op.Destiny" },
{ en: "Cowboy Bebop", jp: "カウボーイビバップ" },
{ en: "Legend of the Galactic Heroes", jp: "銀河英雄伝説" },
{ en: "My Senpai is Annoying", jp: "先輩がうざい後輩の話" },
{ en: "Kaginado", jp: "かぎなど" },
{ en: "Yondemasuyo Azazel-san Z", jp: "よんでますよ、アザゼルさん。Z" },
{ en: "Ousama Ranking", jp: "王様ランキング" },
{ en: "My Neighbor Totoro", jp: "となりのトトロ" },
{ en: "Polar Bear Cafe", jp: "しろくまカフェ" },
{ en: "Akagi", jp: "アカギ" },
{ en: "Binbou Shimai Monogatari", jp: "貧乏姉妹物語" },
{ en: "Sekai Saikou no Ansatsusha, Isekai…", jp: "世界最高の暗殺者、異世界貴族に転生する" },
{ en: "Kamichu!", jp: "かみちゅ！" },
{ en: "Koufuku Graffiti", jp: "幸腹グラフィティ" },
{ en: "Nyanko Days", jp: "にゃんこデイズ" },
{ en: "Ojisan to Marshmallow", jp: "おじさんとマシュマロ" },
{ en: "Kuruneko", jp: "くるねこ" },
{ en: "Teekyuu", jp: "てーきゅう" },
{ en: "Sakugan", jp: "サクガン" },
{ en: "Platinum End", jp: "プラチナエンド" },
{ en: "Super Crooks", jp: "スーパークルックス" },
{ en: "Baki", jp: "バキ" },
{ en: "Chitose Get You!!", jp: "ちとせげっちゅ!!" },
{ en: "Carnival Phantasm", jp: "カーニバル・ファンタズム" },
{ en: "Maou Jou De Oyasumi", jp: "魔王城でおやすみ" },
{ en: "Ascendance of a Bookworm", jp: "本好きの下剋上" },
{ en: "World Trigger", jp: "ワールドトリガー" },
{ en: "Uchuu Kyoudai", jp: "宇宙兄弟" },
{ en: "Arslan Senki", jp: "アルスラーン戦記" },
{ en: "Sorairo Utility", jp: "空色ユーティリティ" },
{ en: "Grimms Notes", jp: "グリムノーツ" },
{ en: "Slow Loop", jp: "スローループ" },
{ en: "My Dress-Up Darling", jp: "その着せ替え人形は恋をする" },
{ en: "Akebi-chan no Sailor Fuku", jp: "明日ちゃんのセーラー服" },
{ en: "Sabikui Bisco", jp: "錆喰いビスコ" },
{ en: "Tensai Ouji No Akaji Kokka Saisei Jutsu", jp: "天才王子の赤字国家再生術" },
{ en: "Yama no Susume", jp: "ヤマノススメ" },
{ en: "Irodorimidori", jp: "いろどりみどり" },
{ en: "Penguin Highway", jp: "ペンギン・ハイウェイ" },
{ en: "Cider no You ni Kotoba ga Wakiagary", jp: "サイダーのように言葉が湧き上がる" },
{ en: "Police in a Pod", jp: "ハコヅメ〜交番女子の逆襲〜" },
{ en: "School Rumble", jp: "スクールランブル" },
{ en: "Namiuchigiwa no Muromi-san", jp: "波打際のむろみさん" },
{ en: "Bokura ga Ita", jp: "僕等がいた" },
{ en: "Little Witch Academia", jp: "リトルウィッチアカデミア" },
{ en: "Yu Yu Hakusho", jp: "幽☆遊☆白書" },
{ en: "Girls und Panzer", jp: "ガールズ&パンツァー" },
{ en: "Aharen-san wa Hakarenai", jp: "阿波連さんははかれない" },
{ en: "Tomodachi Game", jp: "友達ゲーム" },
{ en: "Denpa Onna to Seishun Otoko", jp: "電波女と青春男" },
{ en: "Deaimon", jp: "であいもん" },
{ en: "RPG Fudousan", jp: "RPG不動産" },
{ en: "Spy x Family", jp: "SPY×FAMILY" },
{ en: "Miss Shachiku and the Little Baby Ghost", jp: "社畜さんは幼女幽霊に癒されたい。" },
{ en: "Heroine Tarumono! Kiraware Heroine", jp: "ヒロインたるもの！〜嫌われヒロインと内緒のお仕事〜" },
{ en: "Atasha Kawajiri Kodama Da Yo", jp: "あたしゃ川尻こだまだよ" },
{ en: "In The Heart Of Kunoichi Tsubaki", jp: "くノ一ツバキの胸の内" },
{ en: "Kawaii dake ja Nai Shikimori-san", jp: "可愛いだけじゃない式守さん" },
{ en: "Takunomi", jp: "たくのみ。" },
{ en: "By The Grace Of The Gods", jp: "神達に拾われた男" },
{ en: "Ya Boy Kongming!", jp: "パリピ孔明" },
{ en: "Elegant Yokai Apartment Life", jp: "妖怪アパートの幽雅な日常" },
{ en: "Hana Yamata", jp: "ハナヤマタ" },
{ en: "Karakuri Circus", jp: "からくりサーカス" },
{ en: "Samurai Flamenco", jp: "サムライフラメンコ" },
{ en: "Chibi Devi", jp: "ちび☆デビ！" },
{ en: "Don’t Hurt Me, My Healer!", jp: "このヒーラー、めんどくさい" },
{ en: "Bubble", jp: "バブル" },
{ en: "Kotarou wa Hitorigurashi", jp: "コタローは1人暮らし" },
{ en: "Summertime Render", jp: "サマータイムレンダ" },
{ en: "Love After World Domination", jp: "恋は世界征服のあとで" },
{ en: "Space Patrol Luluco", jp: "宇宙パトロールルル子" },
{ en: "Free", jp: "Free!" },
{ en: "Yakitate!! Japan", jp: "焼きたて!! ジャぱん" },
{ en: "Sailor Moon", jp: "美少女戦士セーラームーン" },
{ en: "Onipan!", jp: "鬼パン!" },
{ en: "I’m Quitting Heroing", jp: "勇者、辞めます" },
{ en: "Warau Arsnotoria Sun!", jp: "咲う アルスノトリア すんっ！" },
{ en: "The Yakuza’s Guide to Babysitting", jp: "組長娘と世話係" },
{ en: "Soredomo Ayumu wa Yosetekuru", jp: "それでも歩は寄せてくる" },
{ en: "Isekai Yakkyoku", jp: "異世界薬局" },
{ en: "Teppen", jp: "てっぺんっ!!!!!!!!!!!!!!!" },
{ en: "Musashino!", jp: "武蔵野!" },
{ en: "Isekai Ojisan", jp: "異世界おじさん" },
{ en: "Lycoris Recoil", jp: "リコリス・リコイル" },
{ en: "Yofukashi no Uta", jp: "よふかしのうた" },
{ en: "Love Live! Superstar!!", jp: "ラブライブ！スーパースター!!" },
{ en: "Magical Witch Punie-Chan", jp: "大魔法峠" },
{ en: "The Maid I Hired Recently Is Mysterious", jp: "最近雇ったメイドが怪しい" },
{ en: "Gingitsune: Messenger Fox of the Gods", jp: "ぎんぎつね" },
{ en: "GA: Geijutsuka Art Design Class", jp: "GA 芸術科アートデザインクラス" },
{ en: "Hidamari Sketch", jp: "ひだまりスケッチ" },
{ en: "Claymore", jp: "クレイモア" },
{ en: "Banished From the Heroes’ Party", jp: "真の仲間じゃないと勇者のパーティーを追い出されたので、辺境でスローライフすることにしました" },
{ en: "Hakumei and Mikochi", jp: "ハクメイとミコチ" },
{ en: "Aiura", jp: "あいうら" },
{ en: "Strange+", jp: "ストレンジ・プラス" },
{ en: "Prima Doll", jp: "プリマドール" },
{ en: "Morita-san wa Mukuchi", jp: "森田さんは無口" },
{ en: "Haruchika: Haruta & Chika", jp: "ハルチカ〜ハルタとチカは青春する〜" },
{ en: "Girlish Number", jp: "ガーリッシュナンバー" },
{ en: "Poco’s Udon World", jp: "うどんの国の金色毛鞠" },
{ en: "Gankutsuo", jp: "巌窟王" },
{ en: "Do It Yourself!!", jp: "Do It Yourself!! -どぅー・いっと・ゆあせるふ-" },
{ en: "The Little Lies We All Tell", jp: "4人はそれぞれウソをつく" },
{ en: "Beast Tamer", jp: "勇者パーティーを追放されたビーストテイマー、最強種の猫耳少女と出会う" },
{ en: "Akiba Maid War", jp: "アキバ冥途戦争" },
{ en: "Chainsaw Man", jp: "チェンソーマン" },
{ en: "Bocchi the Rock!", jp: "ぼっち・ざ・ろっく！" },
{ en: "Magic of Stella", jp: "ステラのまほう" },
{ en: "Dropout Idol Fruit Tart", jp: "落第アイドル果汁100％" },
{ en: "The Eminence in Shadow", jp: "陰の実力者になりたくて！" },
{ en: "Princess Principal", jp: "プリンセス・プリンシパル" },
{ en: "Blue Lock", jp: "ブルーロック" },
{ en: "Alice in Borderland", jp: "今際の国のアリス" },
{ en: "Urusei Yatsura", jp: "うる星やつら" },
{ en: "Gakuen Alice", jp: "学園アリス" },
{ en: "Cyberpunk", jp: "サイバーパンク エッジランナーズ" },
{ en: "Tomo-chan Is a Girl!", jp: "トモちゃんは女の子！" },
{ en: "Spy Classroom", jp: "スパイ教室" },
{ en: "NieR", jp: "ニーア オートマタ" },
{ en: "Planetes", jp: "プラネテス" },
{ en: "The Vampire Dies in No Time", jp: "吸血鬼すぐ死ぬ" },
{ en: "Buddy Daddies", jp: "バディ・ダディーズ" },
{ en: "Hikari no Ou", jp: "火狩りの王" },
{ en: "The Ice Guy and His Cool Female Colleague", jp: "氷属性男子とクールな同僚女子" },
{ en: "Trigun Stampede", jp: "TRIGUN STAMPEDE" },
{ en: "Sugar Apple Fairy Tail", jp: "シュガーアップル・フェアリーテイル" },
{ en: "High Card", jp: "ハイカード" },
{ en: "22/7", jp: "22/7" },
{ en: "Ao Ashi", jp: "アオアシ" },
{ en: "My Clueless First Friend", jp: "事情を知らない転校生がグイグイくる。" },
{ en: "My Home Hero", jp: "マイホームヒーロー" },
{ en: "Jigokuraku", jp: "地獄楽" },
{ en: "The Dangers in my Heart", jp: "僕の心のヤバイやつ" },
{ en: "Ippon! Again", jp: "もういっぽん！" },
{ en: "Tsurune", jp: "ツルネ" },
{ en: "Mashle", jp: "マッシュル-MASHLE-" },
{ en: "Heavenly Delusion", jp: "天国大魔境" },
{ en: "Oshi no Ko", jp: "【推しの子】" },
{ en: "Kawaisugi Crisis", jp: "かわいすぎクライシス" },
{ en: "Otonari ni Ginga", jp: "おとなりに銀河" },
{ en: "Skip and Loafer", jp: "スキップとローファー" },
{ en: "Yuri Is My Job!", jp: "私の百合はお仕事です！" },
{ en: "Birdie Wing", jp: "BIRDIE WING -Golf Girls' Story-" },
{ en: "Otaku Elf", jp: "江戸前エルフ" },
{ en: "Soremachi", jp: "それでも町は廻っている" },
{ en: "Magical Revolution Reincarnated Princess", jp: "魔法少女マジカルデストロイヤーズ" },
{ en: "Ranma 1/2", jp: "らんま1/2" },
{ en: "Kubo Won’t Let Me Be Invisible", jp: "久保さんは僕を許さない" },
{ en: "Magical Girl Magical Destroyers", jp: "魔法少女マジカルデストロイヤーズ" },
{ en: "Loving Yamada at Lv999", jp: "山田くんとLv999の恋をする" },
{ en: "Inuyashiki", jp: "いぬやしき" },
{ en: "Steel Angel Kurumi", jp: "鋼鉄天使くるみ" },
{ en: "Ramen Fighter Miki", jp: "ラーメン大好き小泉さん" },
{ en: "D4DJ", jp: "D4DJ" },
{ en: "The Girl I Like Forgot Her Glasses", jp: "好きな子がめがねを忘れた" },
{ en: "My Tiny Senpai", jp: "うちの会社の小さい先輩の話" },
{ en: "Level 1 Demon Lord and One Room Hero", jp: "レベル1の魔王とワンルーム勇者" },
{ en: "Liar Liar", jp: "LIAR・LIAR" },
{ en: "Zom 100: Bucket List of the Dead", jp: "ZOM100〜ゾンビになるまでにしたい100のこと〜" },
{ en: "Ayaka", jp: "AYAKA -あやか-" },
{ en: "Dark Gathering", jp: "ダークギャザリング" },
{ en: "Bang Dream!", jp: "BanG Dream!" },
{ en: "Helck", jp: "Helck" },
{ en: "Revenue Starlight", jp: "少女☆歌劇 レヴュースタァライト" },
{ en: "Undead Murder Farce", jp: "アンデッドガール・マーダーファルス" },
{ en: "My Happy Marriage", jp: "わたしの幸せな結婚" },
{ en: "Sweet Reincarnation", jp: "スイート・リィンカーネーション" },
{ en: "Haitai Nanafa", jp: "はいたい七葉" },
{ en: "WorldEnd", jp: "終末なにしてますか？忙しいですか？救ってもらっていいですか？" },
{ en: "Ouran High School Host Club", jp: "桜蘭高校ホスト部" },
{ en: "Suzume’s Door Locking", jp: "すずめの戸締まり" },
{ en: "How a Realist Hero Rebuilt the Kingdom", jp: "現実主義勇者の王国再建記" },
{ en: "Slayers", jp: "スレイヤーズ" },
{ en: "The Great Cleric", jp: "聖者無双" },
{ en: "The Most Heretical Last Boss Queen", jp: "最果てのパラディン" },
{ en: "Yohane the Parhelion", jp: "ヨハネザパーヘリオン -SUNSHINE in the MIRROR-" },
{ en: "Ojou to Banken-kun", jp: "お嬢と番犬くん" },
{ en: "Frieren: Beyond Journey’s End", jp: "フリーレン 〜旅の終わりの後に〜" },
{ en: "The Saint’s Magic Power is Omnipotent", jp: "聖女の魔力は万能です" },
{ en: "Ron Kamonohashi’s Forbidden Deductions", jp: "鴨乃橋ロンの禁断推理" },
{ en: "UNDER NINJA", jp: "アンダーニンジャ" },
{ en: "Firefighter Daigo", jp: "め組の大吾" },
{ en: "The Yuzuki Family’s Four Sons", jp: "柚木家四兄弟" },
{ en: "My New Boss Is Goofy", jp: "新しい上司はど天然" },
{ en: "The Family Circumstances of the Witch", jp: "魔女の家計事情" },
{ en: "The Kingdoms of Ruin", jp: "破滅の国の愛" },
{ en: "Castlevania", jp: "キャッスルヴァニア" },
{ en: "The Apothecary Diaries", jp: "薬屋のひとりごと" },
{ en: "I’m in Love with the Villainess", jp: "私の推しは悪役令嬢" },
{ en: "The Blue Orchestra", jp: "青のオーケストラ" },
{ en: "Pluto", jp: "プルートゥ" },
{ en: "Tearmoon Empire", jp: "ティアムーン帝国物語" },
{ en: "Undead Unlock", jp: "アンデッドアンラック" },
{ en: "Our Dating Story: The Experienced You", jp: "経験済みなキミと、経験ゼロなオレが、お付き合いする話" },
{ en: "Stardust Telepath", jp: "スターダスト・テレパス" },
{ en: "Dead Mount Death Play", jp: "デッドマウント・デスプレイ" },
{ en: "Shangri-La Frontier", jp: "シャングリラ・フロンティア" },
{ en: "Kay’s Daily Doodles", jp: "けいどろ日記" },
{ en: "Delicious In Dungeon", jp: "ダンジョン飯" },
{ en: "The Way of Pon", jp: "ぽんこつちゃん道をゆく" },
{ en: "Sasaki and Peeps", jp: "佐々木とピーちゃん" },
{ en: "A Sign of Affection", jp: "ゆびさきと恋々" },
{ en: "Fluffy Paradise", jp: "もふもふパラダイス" },
{ en: "Solo Leveling", jp: "ソロレベリング" },
{ en: "7th Time Loop", jp: "七度目のループ" },
{ en: "The Unwanted Undead Adventurer", jp: "望まぬ不死の冒険者" },
{ en: "Mr. Villain’s Day Off", jp: "悪役令嬢は休暇中" },
{ en: "Tis Time For “Torture” Princess", jp: "姫様“拷問”の時間です" },
{ en: "Belle", jp: "竜とそばかすの姫" },
{ en: "Villainess Level 99", jp: "悪役令嬢レベル99" },
{ en: "Sengoku Youko", jp: "戦国妖狐" },
{ en: "Doctor Elise: The Royal Lady With The Lamp", jp: "ドクター・エリーゼ" },
{ en: "Ishura", jp: "異修羅" },
{ en: "The Weakest Tamer Began a Journey", jp: "最弱テイマーはゴミ拾いの旅を始めました。" },
{ en: "Chiikawa", jp: "ちいかわ" },
{ en: "Yumeiro Patissiere", jp: "夢色パティシエール" },
{ en: "Ninja Kamui", jp: "忍者神風" },
{ en: "Train to the End of the World", jp: "世界の果ての電車" },
{ en: "Re:Monster", jp: "リ・モンスター" },
{ en: "Reincarnated Aristocrat, Appraisal Skill", jp: "転生貴族、鑑定スキルで成り上がる　～弱小領地を受け継いだので、優秀な人材を増やしていたら、最強領地になってた～" },
{ en: "Bartender Glass of God", jp: "バーテンダー 神のグラス" },
{ en: "Level 2 Super Cheat Powers", jp: "レベル2のスーパー・チート能力" },
{ en: "The Fable", jp: "ザ・ファブル" },
{ en: "Jellyfish can’t swim in the night", jp: "クラゲは夜泳げない" },
{ en: "Tonari no Yokai-san", jp: "となりの妖怪さん" },
{ en: "GO! GO! Loser Ranger!", jp: "ゴーゴー・レンジャー" },
{ en: "An Archdemon’s Dilemma", jp: "大魔王様の家庭事情" },
{ en: "WIND BREAKER", jp: "ウィンドブレイカー" },
{ en: "Sand Land: The Series", jp: "サンドランド" },
{ en: "Boukyaku Battery", jp: "忘却バッテリー" },
{ en: "Kaii to Otome to Kamikakushi", jp: "怪異と乙女と神隠し" },
{ en: "Astro Note", jp: "アストロノート" },
{ en: "The Grimm Variations", jp: "グリムバリエーションズ" },
{ en: "Ragna Crimson", jp: "ラグナクリムゾン" },
{ en: "The Ossan Newbie Adventurer", jp: "おっさん冒険者の新人" },
{ en: "Alya Sometimes Hides Her Feelings Russian", jp: "アリヤはロシアで隠れたがる" },
{ en: "I Parry Everything", jp: "俺、全部パリるから" },
{ en: "Failure Frame", jp: "失格紋の最強賢者" },
{ en: "Quality Assurance in Another World", jp: "異世界品質保証" },
{ en: "My Deer Friend Nokotan", jp: "しかのこのこのここしたんたん" },
{ en: "Dungeon People", jp: "ダンジョンピープル" },
{ en: "Sakuna: Of Rice And Ruin", jp: "天穂のサクナヒメ" },
{ en: "SHOSHIMIN", jp: "しょしみん" },
{ en: "The Elusive Samurai", jp: "逃げ上手の若君" },
{ en: "Dahlia in Bloom", jp: "ダリア・イン・ブルーム" },
{ en: "TASUKETSU", jp: "たすけつ" },
{ en: "A Journey Through Another World:Raising Kids", jp: "異世界ゆるり紀行" },
{ en: "ATRI: My Dear Moments", jp: "ATRI -My Dear Moments-" },
{ en: "Makeine: Too Many Losing Heroines!", jp: "負けヒロインが多すぎる！" },
{ en: "MAYONAKA PUNCH", jp: "深夜パンチ" },
{ en: "Bye Bye, Earth", jp: "ばいばい、アース" },
{ en: "Head Start at Birth", jp: "0歳児スタートダッシュ物語" },
    ];

    const queueAnimeList = [
        { en: "Red Cat Ramen", jp: "赤い猫のラーメン" }
    ];

    const container = document.querySelector('main');
    const counter = document.getElementById('animeCounter');

    const searchBar = document.getElementById('searchBar');
    const watchedButton = document.getElementById('watchedButton');
    const queueButton = document.getElementById('queueButton');
    const langENButton = document.getElementById('langEN');
    const langJPButton = document.getElementById('langJP');
    const titleElement = document.querySelector('header h1');

    let currentList = watchedAnimeList;
    let currentLang = 'EN';

    searchBar.addEventListener('input', filterAnimeList);
    watchedButton.addEventListener('click', () => switchList('watched'));
    queueButton.addEventListener('click', () => switchList('queue'));
    langENButton.addEventListener('click', () => switchLanguage('EN'));
    langJPButton.addEventListener('click', () => switchLanguage('JP'));

    function switchList(list) {
        if (list === 'watched') {
            currentList = watchedAnimeList;
            watchedButton.classList.add('active');
            queueButton.classList.remove('active');
            titleElement.textContent = 'Watched Animes';
            counter.textContent = `Total Watched Anime: ${currentList.length}`;
        } else if (list === 'queue') {
            currentList = queueAnimeList;
            queueButton.classList.add('active');
            watchedButton.classList.remove('active');
            titleElement.textContent = 'Watchlist';
            counter.textContent = `Total Queued Anime: ${currentList.length}`;
        }
        filterAnimeList();
    }

    function switchLanguage(lang) {
        currentLang = lang;
        langENButton.classList.toggle('active', lang === 'EN');
        langJPButton.classList.toggle('active', lang === 'JP');
        updateAnimeTitles();
    }

    function updateAnimeTitles() {
        const animeCards = document.querySelectorAll('.anime-card');
        animeCards.forEach(card => {
            const titleElement = card.querySelector('h2');
            const englishTitle = titleElement.getAttribute('data-en-title');
            const japaneseTitle = titleElement.getAttribute('data-jp-title');
            titleElement.textContent = currentLang === 'EN' ? englishTitle : japaneseTitle;
        });
    }

    function displayAnimeList(list) {
        container.innerHTML = '';
        list.forEach(anime => {
            const animeCard = document.createElement('div');
            animeCard.classList.add('anime-card');

            const animeImage = document.createElement('img');
            const formattedAnime = formatTitle(anime.en);

            const imageSrc = `images/${formattedAnime}.jpg`;
            imageExists(imageSrc, function (exists) {
                animeImage.src = exists ? imageSrc : 'images/default.jpg';
            });

            animeImage.alt = anime.en;
            const animeTitle = document.createElement('h2');
            animeTitle.setAttribute('data-en-title', anime.en);
            animeTitle.setAttribute('data-jp-title', anime.jp);
            animeTitle.textContent = currentLang === 'EN' ? anime.en : anime.jp;

            animeCard.appendChild(animeImage);
            animeCard.appendChild(animeTitle);
            container.appendChild(animeCard);
        });
        updateCounter(list.length);
    }

    function filterAnimeList() {
        const searchText = searchBar.value.toLowerCase();
        const filteredList = currentList.filter(anime => anime.en.toLowerCase().includes(searchText) || anime.jp.toLowerCase().includes(searchText));
        displayAnimeList(filteredList);
    }

    function imageExists(url, callback) {
        const img = new Image();
        img.onload = () => callback(true);
        img.onerror = () => callback(false);
        img.src = url;
    }

    function formatTitle(title) {
        return title.replace(/[^\w\s-]/g, '').toLowerCase().replace(/[\s-]+/g, '');
    }

    function updateCounter(count) {
        if (currentList === watchedAnimeList) {
            counter.textContent = `Total Watched Anime: ${count}`;
        } else {
            counter.textContent = `Total Queued Anime: ${count}`;
        }
    }

    switchList('watched');
}

document.addEventListener('DOMContentLoaded', () => {
    const banners = [
        { img: 'images/bannergintama.jpg', title: 'Gintama', description: 'The Amanto, vicious aliens from outer space, has taken over the country of Japan. It has suppressed all the samurais by prohibiting the usage of samurai swords. Sakata Gintoki is one of the few remaining samurai. Along with Shimura… Gintama is a rare case that is rated G for everyone. Every single episode in the series has unique storyline and actions. The story follows Gintoki as he assists victims of the the Amanto’s invasion by fighting with the shinsengumi and the aliens.' },
        { img: 'images/bannersg.jpg', title: 'Steins;Gate', description: 'The story of Steins;Gate takes place in Akihabara and is about a group of friends who have managed to customize their microwave into a device that can send text messages to the past. As they perform different experiments, an organization named SERN who has been doing their own research on time travel tracks them down and now the characters have to find a way to avoid being captured by them.' },
        { img: 'images/bannermia.jpg', title: 'Made In Abyss', description: 'The enormous cave system, known as the Abyss, is the only unexplored place in the world. Nobody knows how deep down goes this titanic pit, inhabited by strange and wondrous creatures and full of mysterious ancient relics which purpose in unknown to modern man. Generations of bold adventurers have been drawn by the cryptic depths of the Abyss. In course of time those bold enough to explore the dangerous pit came to be known as "Cave Raiders." In Oosu, the town at the edge of the Abyss, there lives a little orphan named Riko, who dreams of becoming as great a cave raider as her mother was and solving the great mystery of the pit. One day exploring the murky depths she stumbles upon a little boy, who turns out to be a robot...' },
        { img: 'images/bannerhxh.jpg', title: 'Hunter X Hunter', description: 'Hunter X Hunter revolves around Gon Freecss whose goal in life is to find his father Ging, a renowned hunter. In order to find his father, Gon must become a hunter himself and sets out to do so. Along the way, he meets Kurapika, Leorio, and Killua. Together they set out to take the Hunter Exam and Gon’s quest to become a legendary hunter begins.' },
        { img: 'images/bannerdn.jpg', title: 'Death Note', description: 'Death Note follows Light Yagami, a high school student who discovers a mysterious notebook that grants him the power to kill anyone whose name he writes in it. Using the alias Kira, Light embarks on a mission to rid the world of criminals, attracting the attention of the genius detective L. A tense cat-and-mouse game ensues as L attempts to uncover Kira\'s identity and stop his reign of terror. The series explores themes of justice, morality, and the corrupting influence of power.' },
        { img: 'images/bannerjojo.jpg', title: 'Jojo', description: 'JoJo\'s Bizarre Adventure follows the adventures of the Joestar family, whose members possess unique supernatural abilities. Each part of the series focuses on a different member of the family as they battle various foes using their powers. The story spans multiple generations, blending action, fantasy, and eccentric characters. Known for its distinctive art style and imaginative battles, the series has become a beloved classic in the anime world.' },
        { img: 'images/bannerclannad.jpg', title: 'Clannad', description: 'Clannad follows the story of Tomoya Okazaki, a delinquent high school student, and his encounters with various classmates as he helps them overcome their personal struggles. The series delves into themes of family, friendship, and love, with a strong emphasis on emotional storytelling. As Tomoya forms deeper connections with his friends, he begins to find purpose and meaning in his life.' },
        { img: 'images/bannerkdm.jpg', title: 'Kobayashi Dragon-Maid', description: 'Miss Kobayashi\'s Dragon Maid follows the life of Kobayashi, an office worker, who unexpectedly ends up living with a dragon named Tohru who can transform into a human maid. As Tohru adjusts to human life and Kobayashi\'s friends meet other dragons, they form a unique and heartwarming family. The series blends comedy, fantasy, and slice-of-life elements, highlighting the humorous and touching moments of their daily lives. It is known for its charming characters and lighthearted storytelling.' },
        { img: 'images/banneronk.jpg', title: 'Oshi No Ko', description: 'Sixteen-year-old Ai Hoshino is a talented and beautiful idol who is adored by her fans. She is the personification of a pure, young maiden. But all that glitters is not gold. Gorou Amemiya is a countryside gynecologist and a big fan of Ai. So when the pregnant idol shows up at his hospital, he is beyond bewildered. Gorou promises her a safe delivery. Little does he know, an encounter with a mysterious figure would result in his untimely death—or so he thought. Opening his eyes in the lap of his beloved idol, Gorou finds that he has been reborn as Aquamarine Hoshino—Ai\'s newborn son! With his world turned upside down, Gorou soon learns that the world of showbiz is paved with thorns, where talent does not always beget success. Will he manage to protect Ai\'s smile that he loves so much with the help of an eccentric and unexpected ally?' },
        { img: 'images/bannerfrn.jpg', title: 'Frieren', description: 'The demon king has been defeated, and the victorious hero party returns home before disbanding. The four—mage Frieren, hero Himmel, priest Heiter, and warrior Eisen—reminisce about their decade-long journey as the moment to bid each other farewell arrives. But the passing of time is different for elves, thus Frieren witnesses her companions slowly pass away one by one. Before his death, Heiter manages to foist a young human apprentice called Fern onto Frieren. Driven by the elf\'s passion for collecting a myriad of magic spells, the pair embarks on a seemingly aimless journey, revisiting the places that the heroes of yore had visited. Along their travels, Frieren slowly confronts her regrets of missed opportunities to form deeper bonds with her now-deceased comrades.' },
    ];

    let currentBanner = 0;
    const bannerElement = document.getElementById('banner');
    const bannerTitle = document.getElementById('bannerTitle');
    const bannerDescription = document.getElementById('bannerDescription');
    const bannerIndicator = document.getElementById('bannerIndicator');

    function updateBanner() {
        const { img, title, description } = banners[currentBanner];
        bannerElement.style.backgroundImage = `url(${img})`;
        bannerTitle.textContent = title;
        bannerDescription.textContent = description;
    }

    function nextBanner() {
        currentBanner = (currentBanner + 1) % banners.length;
        updateBanner();
    }

    function prevBanner() {
        currentBanner = (currentBanner - 1 + banners.length) % banners.length;
        updateBanner();
    }

    // Initialize the banner
    updateBanner();
    // Set interval for banner rotation
    let bannerInterval = setInterval(nextBanner, 5000);

    bannerElement.addEventListener('mouseenter', () => {
        clearInterval(bannerInterval);
        bannerIndicator.style.display = 'block'; // Show the indicator
    });

    bannerElement.addEventListener('mouseleave', () => {
        bannerInterval = setInterval(nextBanner, 5000);
        bannerIndicator.style.display = 'none'; // Hide the indicator
    });

    // Add event listeners to the arrow buttons
    document.querySelector('.banner-arrow.left').addEventListener('click', prevBanner);
    document.querySelector('.banner-arrow.right').addEventListener('click', nextBanner);
});
